// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApICLGXFP3QXLPYzWWS__m_ZrD1VygvIw',
    appId: '1:1081016818550:web:485d85a0b3e1aef4cab857',
    messagingSenderId: '1081016818550',
    projectId: 'petukji-f9fb5',
    authDomain: 'petukji-f9fb5.firebaseapp.com',
    storageBucket: 'petukji-f9fb5.appspot.com',
    measurementId: 'G-S7Z0B35PCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3ngwepbJjJyECy5ZJVm_2A2zK3-R1nI',
    appId: '1:1081016818550:android:e5e328da67204cdccab857',
    messagingSenderId: '1081016818550',
    projectId: 'petukji-f9fb5',
    storageBucket: 'petukji-f9fb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_UekRv3yYBgql8fRrHqWY3SkTjXJneW8',
    appId: '1:1081016818550:ios:4f335b8d206e80d5cab857',
    messagingSenderId: '1081016818550',
    projectId: 'petukji-f9fb5',
    storageBucket: 'petukji-f9fb5.appspot.com',
    iosClientId: '1081016818550-a333b4udaam4sqrsjqds7vo4jfv335b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_UekRv3yYBgql8fRrHqWY3SkTjXJneW8',
    appId: '1:1081016818550:ios:ec7c589efd984fdfcab857',
    messagingSenderId: '1081016818550',
    projectId: 'petukji-f9fb5',
    storageBucket: 'petukji-f9fb5.appspot.com',
    iosClientId: '1081016818550-tr6leetndhsdkqq8akkr9pq6kshnb6cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
